### ISSUE TITLE
Consider PHPSci as computing library

### ISSUE THREAD

**Issue by henrique-borba** [AndrewCarterUK/mnist-neural-network-plain-php#1]
Hi @AndrewCarterUK 

I'm currently trying to solve PHP slow array computing with PHPSci (https://www.github.com/phpsci/phpsci), its inspired by NumPy.

It's currently under development but operations like matmul out performs PHP array in a factor of 900.

Any help would be nice.

**Comment by AndrewCarterUK** [comment]
That looks really nice - good work!

This repository is supposed to just be an example of the mechanics of a neural network rather than a useful project, so I'd prefer to stick to PHP basics for the main branch.

That said, I'd be more than happy to have a `phpsci` branch and put a note in the README with a link to the source tree and your library if you like?

**Comment by henrique-borba** [comment]
That would be great Andrew! Thank you.

I'll make a fork of your example to test the difference and performance gains during development, after all it's not every day that we find MNIST implementations in PHP.

See you and thank you again.
